INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (1, 1)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (2, 1)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (3, 1)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (4, 1)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (5, 1)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (6, 1)

INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (7, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (8, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (9, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (10, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (11, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (12, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (13, 2)
INSERT INTO [dbo].[Product_Category] ([Id_Product], [id_Category]) VALUES (14, 2)